### ISSUE TITLE
Can I paire with Bluetooth BLE

### ISSUE THREAD

**Issue by pingpop** [edufolly/flutter_bluetooth_serial#67]
Can I pair with Bluetooth BLE.

How to set it

It's required password every time but Bluetooth BLE is not a pin

Thanks

**Comment by PsychoXIVI** [comment]
Pairing process for BLE devices should be similar like for Bluetooth Classic/Serial I think, but I am not 100% sure. Using this library you can request pairing to the devices, but you might be unable exchange data (since the library support Bluetooth Classic/Serial communication).

_BTW, did you saw #18, point `F)`? Are you sure you want to use this library for BLE?_

Anyway, for pairing, you should look at bonding example on long press at `DiscoveryPage`:

https://github.com/edufolly/flutter_bluetooth_serial/blob/412f1aec7b92fb335248801a0bf0a0e82df4de3f/example/lib/DiscoveryPage.dart#L95-L116

See [here for `bondDeviceAtAddress` documented](https://pub.dev/documentation/flutter_bluetooth_serial/latest/flutter_bluetooth_serial/FlutterBluetoothSerial/bondDeviceAtAddress.html) more widely - you can even request bonding with automatic filling pin/accepting password handler.

You can also setup custom handler for pairing requests to make the app answer such requests:

https://github.com/edufolly/flutter_bluetooth_serial/blob/412f1aec7b92fb335248801a0bf0a0e82df4de3f/example/lib/MainPage.dart#L192-L197

There are few pairing variants, most common are `Pin`, `PasskeyConfirmation` and `Consent`. 

Also, the [`setPairingRequestHandler` is documented](https://pub.dev/documentation/flutter_bluetooth_serial/latest/flutter_bluetooth_serial/FlutterBluetoothSerial/setPairingRequestHandler.html).

Please note, these might not work at your device - since your system might enforce user activity on pairing to improve security. 

_I also noticed now, that the handler want user to return `Future`, it might change in next versions to `Future` or normal value._
